### ISSUE TITLE
Facilitate testing order of events?

### ISSUE THREAD

**Issue by ralphtheninja** [vweevers/stream-test#1]
I was thinking (maybe premature) that we could make it easier to test order of events by pulling in `stream-observer` and implementing the `monitor` functionality we use in `level-ws` and `level-iterator-stream` etc.

@vweevers Not a fully baked idea, but maybe it fits better in your head :smile:

**Comment by vweevers** [comment]
https://github.com/vweevers/stream-test/blob/ccfeb431c107ff73636dcf512b53362b3a714b50/readable.js#L165-L174

**Comment by ralphtheninja** [comment]
Haha, ahead of me :wink:
